stages:
  - build-images
  - tests

# Base template for creating image on-demand.
.build-test-image:
  stage: build-images
  # This base image includes bash and docker, and was created manually.
  image: "$CI_REGISTRY_IMAGE:builder"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd ci
    - ./build-image-if-needed "$CI_REGISTRY_IMAGE" "$IMAGE_TAG"
  tags:
    - linux

variables:
  # If we need to update llvm we can just change the version here, and the
  # image will be recreated.
  LINUX_IMAGE_TAG: "ubuntu-focal-build-20220617-llvm-15"

# If we'd need to create another image we'd duplicate this job, and create a
# new image tag.
build-linux-image:
  extends: .build-test-image
  variables:
    IMAGE_TAG: $LINUX_IMAGE_TAG

test-linux:
  stage: tests
  image: "$CI_REGISTRY_IMAGE:$LINUX_IMAGE_TAG"
  needs:
    - build-linux-image
  tags:
    - linux
  script:
    - mkdir build && cd build
    - cmake .. -G Ninja
    - ninja
    - ctest --output-on-failure
