test:
  image: "$CI_REGISTRY_IMAGE:llvm9"
  tags:
    - docker
    - linux
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=clang-9 -DCMAKE_CXX_COMPILER=clang++-9 && make
    - ctest --output-on-failure
