stages:
  - build
  - test

build:
  script:
    - cd /Users/esaillar/Documents/PARCOACH/parcoach_gitlab/parcoach//build
    - cmake .. -DLLVM_DIR=/Users/esaillar/Documents/TOOLS/LLVM_391/install/lib/cmake/llvm -DCMAKE_C_COMPILER=/Users/esaillar/Documents/TOOLS/LLVM_391/install/bin/clang -DCMAKE_CXX_COMPILER=/Users/esaillar/Documents/TOOLS/LLVM_391/install/bin/clang++
    - make

test:
  script:
    - ctest