stages:
  - build-images
  - build
  - tests
  - upload
  - deploy
  - release

variables:
  # If we need to update llvm we can just change the version here, and the
  # image will be recreated.
  LINUX_IMAGE_TAG: "ubuntu-focal-build-20221125-llvm-15"
  RHEL_IMAGE_TAG: "ubi-8.6-build-20221129-ninja-1.11.1-mpi-4.1.4-llvm-15.0.6-tests-20221130"
  PIPENV_VENV_IN_PROJECT: "true"
  # NOTE: this is not quite accurate as we may get either a small/medium/large
  # runner, but it's better than nothing!
  CTEST_PARALLEL_LEVEL: "4"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/parcoach"

include:
  - "ci/gitlab/anchors.yml"
  - "ci/gitlab/build-images.yml"
  - "ci/gitlab/build.yml"
  - "ci/gitlab/tests.yml"
  - "ci/gitlab/coverage.yml"
  - "ci/gitlab/publish-release.yml"
