build-releases:
  stage: build
  image: "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  needs:
    - build-linux-image
    - build-rhel-image
  tags:
    - linux,large
  parallel: !reference [.release-matrix, parallel]
  script:
    - !reference [.set-version-suffix, script]
    - mkdir build
    - mkdir packages
    - cmake . -G Ninja -B build
      -C caches/Release-${TYPE}.cmake
      -DPARCOACH_VERSION_SUFFIX=$VERSION_SUFFIX
    - cmake --build build --target package
    - mv build/parcoach-*.* packages
  artifacts:
    paths:
      - packages/
    expire_in: 2 days
