set(PARCOACH_BUILD_SHARED ON CACHE BOOL "")
set(CMAKE_BUILD_TYPE Release CACHE STRING "")
# We're just building a release, we don't care about tests.
set(PARCOACH_ENABLE_TESTS OFF CACHE BOOL "")
if(NOT DEFINED PARCOACH_VERSION_SUFFIX)
  set(PARCOACH_VERSION_SUFFIX "-shared" CACHE STRING "")
endif()
