set(PARCOACH_ENABLE_INSTRUMENTATION ON CACHE BOOL "")
set(PARCOACH_ENABLE_FORTRAN ON CACHE BOOL "")
set(PARCOACH_INSTALL_DIR $ENV{PARCOACH_INSTALL_DIR} CACHE STRING "")
set(LLVM_TOOLS_BINARY_DIR $ENV{LLVM_TOOLS_BINARY_DIR} CACHE STRING "")
