set(CMAKE_C_COMPILER clang CACHE STRING "")
set(CMAKE_CXX_COMPILER clang++ CACHE STRING "")
set(PARCOACH_BUILD_SHARED OFF CACHE BOOL "")
set(PARCOACH_ENABLE_COVERAGE ON CACHE BOOL "")
set(PARCOACH_ENABLE_INSTRUMENTATION ON CACHE BOOL "")
set(PARCOACH_DISABLE_INSTRUMENTATION_TESTS ON CACHE BOOL "")
set(PARCOACH_ENABLE_FORTRAN OFF CACHE BOOL "")
set(MPIEXEC_EXECUTABLE "/opt/mpi/openmpi/4.1.4.4/bin/mpiexec" CACHE STRING "")
# We want -g and as few optimizations as possible to be able to have the most
# accurate line coverage.
set(CMAKE_BUILD_TYPE Debug CACHE STRING "")
set(PARCOACH_ENABLE_TESTS ON CACHE BOOL "")
