option(PARCOACH_ENABLE_INSTRUMENTATION "Build PARCOACH instrumentation module." ON)
option(PARCOACH_ENABLE_MPI "Build PARCOACH with MPI support." ON)
option(PARCOACH_ENABLE_OPENMP "Build PARCOACH with OpenMP support." ON)
option(PARCOACH_ENABLE_CUDA "Build PARCOACH with Cuda support." OFF)
option(PARCOACH_ENABLE_UPC "Build PARCOACH with UPC support." OFF)
